
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: readlink_3u64_user
  password: 7qLcTWoHkWySPAz9vcCBIoDyiLN1MJSE
  port: 5432



#development:
#  <<: *default
#  database: readlink_3u64
#
#
#test:
#  <<: *default
#  database: readlink_3u64
#  port: 5432
#
production:
  primary: &primary_production
    <<: *default
    database: readlink_3u64
    username: myapp
    password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: ReadLink_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: ReadLink_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: ReadLink_production_cable
    migrations_paths: db/cable_migrate